apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: pxbbq-web  
  namespace: pxbbq         
spec:
  replicas: 3                    
  template:                      
    spec:                        
      containers:
      - name: pxbbq-web
        image: eshanks16/pxbbq:6bf91d4
        env:        
        - name: CHATBOT_ENABLED #If CHATBOT is set to False, the other variables in this section are not needed.
          value: "True" #Set to True to enable a LLAMA3 chatbot - Requires the AIDemo to be deployed first
        - name: PXBBQ_URI
          value: "http://10.0.1.162" #MUST Be the external svc name for the PXBBQ application (PXBBQ NodePort/LoadBalaner)
        - name: MODEL_SERVER_URI
          value: "http://ollama.genai.svc.cluster.local:11434" #MUST be the internal svc name for the ollama service (CLUSERIP)
        - name: NEO4J_URI
          value: "bolt://database.genai.svc.cluster.local:7687" #MUST be the internal svc name for the new4j service (CLUSTERIP)