apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: harvester1
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: harvester1
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            bootOrder: 1
            name: harddrive
          interfaces:
            - name: bridge-vlan5
              model: virtio
              bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 32G
      networks:
        - name: bridge-vlan5
          multus:
            networkName: bridge-vlan5
            default: true
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: harvester150rc1
      - name: harddrive
        persistentVolumeClaim:
          claimName: harvester1
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: harvester2
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: harvester2
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            bootOrder: 1
            name: harddrive
          interfaces:
            - name: bridge-vlan5
              model: virtio
              bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 32G
      networks:
        - name: bridge-vlan5
          multus:
            networkName: bridge-vlan5
            default: true
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: harvester150rc1
      - name: harddrive
        persistentVolumeClaim:
          claimName: harvester2
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: harvester3
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: harvester3
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            bootOrder: 1
            name: harddrive
          interfaces:
            - name: bridge-vlan5
              model: virtio
              bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 32G
      networks:
        - name: bridge-vlan5
          multus:
            networkName: bridge-vlan5
            default: true
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: harvester150rc1
      - name: harddrive
        persistentVolumeClaim:
          claimName: harvester3
