name: deploy latest utilities

on:
  push:
    branches:
      - main
    paths:
      - 'manifests/utilities/*' # Replace with the path to the file or directory you want to monitor

jobs:
  build:
    name: deploy from main
    runs-on: ubuntu-latest
    steps:
      - name: Replace Secret
        run: |
          sed -i 's|{{ROUTE53_SECRET}}|'"${{ secrets.ROUTE53_SECRET }}"'|' route53-credentials.yaml
        working-directory: manifests/cert-manager
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deployment
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"
          clientSecret: "${{ secrets.CDAAS_CLIENT_SECRET }}"
          path-to-file: "/armory/utilities.yaml"
