name: deploy latest minio

on:
  push:
    branches:
      - main
    paths:
      - 'manifests/minio/*' # Replace with the path to the file or directory you want to monitor
      - 'armory/minio.yaml'

jobs:
  build:
    name: deploy from main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Replace Secret
        run: |
          sed -i 's|{{MINIO_PASSWORD}}|'"${{ secrets.MINIO_PASSWORD }}"'|' minio.yaml
        working-directory: manifests/minio
      - name: Deployment
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"
          clientSecret: "${{ secrets.CDAAS_CLIENT_SECRET }}"
          path-to-file: "/armory/minio.yaml"



