---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: desktop-ingress
  namespace: default
spec:
  encryptedData:
    auth: AgCoO9llMD8Xbvya4G+IRMJMJInjPNcb0jrny3AsOi7vL5LnilYt/9UaZaYQ5kATy68PVDrTX3MXO341UqaWCV5t5rsWjeQc3GbzimmFs9m+rZvthNClwZo5nMKFsalqn1KcgwJSzBGxzxjvLeA6/Th6JVauGG9UeRT333AqtEcqcmFUCv5xFO7shylbx+k8UgUikPRgpFj1RqmmanCCxJP/aOqMhH2s6/1hXAEcj/TSR/oB8RnnJR/ChuBSu5MkWtXDl+Z2TSdsgFa4hKYdQOCuYNcHZh5+zSOnmGkJFMYS9/chmodlkCV5ptq073RCPG1kSR8+WcanVzYtt7BGgn41qVLXoDUC0qtbj+rCPuiUCp0M1MopZBqWZfG3SD5tuYezNx/DYdjvu/296lD54eHwluWmq9w9/FoujAMYsrWS5Pp+A5zyccO2lk8SDlnRCfXc1YXAlqUTwxzN4+Z3fWbey45Auu2nxpGfsT/Y6OgGb35+tjhaJUI4iy77gpJpiFcZGbjGR1dy8pIjuCnCTZM059YBo5/3Ayx+PUOrzMaFD2JMdQjAN1yCmgHtAyCM1HZ2Vrp2/IDAK5pbqJ0LWJxGt9PT/KbYJk9MHGO7cELd+V4Xr/wnISCpfaj5+q1S6oqQ1dMf1JHnJ9WXfpb1biQtwEWXFlBe+zXubNJ+4oa7JbB3aibxrEFoQSJGZyyUB0jcc6SYryzpZGR7UIKYVL2651cBRkgFvLDX34RmCPleoR9yCct9CHFG+yA0hw==
  template:
    metadata:
      creationTimestamp: null
      name: desktop-ingress
      namespace: default
