apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-path"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2025-01-31T02:22:44Z"
  name: local-path-vm
  resourceVersion: "340175"
  uid: 45b550f3-b97d-4f63-a4db-d2e7cb4c194f
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
