apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vm
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridgevm",
      "type": "bridge",
      "vlan": 1,
      "bridge": "br0",
      "ipam": {
        "type": "dhcp"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan1",
      "type": "bridge",
      "bridge": "br1",
      "ipam": {
        "type": "dhcp"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan4
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan4",
      "type": "bridge",
      "bridge": "br4",
      "ipam": {
        "type": "dhcp"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan5
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan5",
      "type": "bridge",
      "bridge": "br5",
      "ipam": {
        "type": "dhcp"
      }
    }'
# ---
# apiVersion: "k8s.cni.cncf.io/v1"
# kind: NetworkAttachmentDefinition
# metadata:
#   name: bridge-vlan5
# spec:
#   config: '{
#       "cniVersion": "0.3.1",
#       "name": "bridge-vlan5",
#       "type": "bridge",
#       "bridge": "br5",
#       "ipam": {
#         "type": "host-local",
#         "ranges": [
#           [
#             {
#               "subnet": "10.0.5.0/24",
#               "rangeStart": "10.0.5.30",
#               "rangeEnd": "10.0.5.99",
#               "gateway": "10.0.5.1"
#             }
#           ]
#         ],
#         "routes": [
#           { "dst": "0.0.0.0/0", "gw": "10.0.5.1" }
#         ],
#         "resolvConf": "/etc/resolv.conf"
#       }
#     }'