apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
  name: ingress-mealie
  namespace: mealie
spec:
  ingressClassName: nginx
  rules:
  - host: mealie.ccrow.org
    http:
      paths:
      - backend:
          service:
            name: mealie
            port:
              number: 9000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mealie.ccrow.org
    secretName: mealie-tls