apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.8.0
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: DB_ENGINE
              value: "sqlite"
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_PASSWORD
              value: "mealie"
            - name: POSTGRES_SERVER
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "mealie"
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
