apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
  labels:
    type: nfs
spec:
  storageClassName: nfs
  capacity:
    storage: 2048Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/gentoo/minio
    server: 10.0.2.8 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: minio
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2048Gi
  selector:
    matchLabels:
      type: nfs