apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-world-data
  namespace: valheim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-local-durable
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-base-data
  namespace: valheim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-local-durable