allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-csi-db
parameters:
  io_profile: db_remote
  repl: "3"
  io_throttle_rd_iops: "750"
  io_throttle_wr_iops: "750"
  #  io_throttle_rd_bw: "10"
  #  io_throttle_wr_bw: "10"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
