apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: gitlab-runner-boot
  namespace: gitlab
spec:
  source:
    http:
      url: "http://registry.lan.ccrow.org:8080/noble-server-cloudimg-amd64.img"
  storage:
    volumeMode: Filesystem
    storageClassName: longhornv2
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-cloudinit-userdata
  namespace: gitlab
type: Opaque
stringData:
  userData: |
    #cloud-config
    hostname: gitlab-runner
    manage_etc_hosts: true
    ssh_pwauth: false
    users:
      - name: ubuntu
        plain_text_passwd: 'ubuntu'
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+kx58yg6pGei4XrdXJhNfkRvfKWhGPUveM90+OGt74DbUc0B/BkfN5enpzEn3IciEOUm65TDQP0f1rmYxxWt9UPJWH2zvaWmaCdq0JUsf+V8N+G5gHpCVNJTMWeogtskpMGIKv7HJMH35RuBnM71ZHeMwTvhb422evYYq+8yUiRUc9B90p4w9Kshl+FjyOsSMn7m+9WS6HjX8Gbp+k8CGxqIrFz6t+ZE/uNmqlDaMZtXgJJIC+QrN/u14AfRX84VktNo4UPUgGmgrnCwk6fs6J5a55R6nEJ1qYHUnqkB+1AjwP2tZocHmeZkQilLT1kQvI3iIEHfyJya/c2zOZbiyu6XRsiYv/h28Ev6eevzoAQjeXq8IN/1PjZogRxgr7MpI/1GaHyq4SNBeCcgU6nk003kL6Y6o7GXTVaZbjCMdK6kF+Oi1MQtGygu4X9iy6pmCsSIIW+rFpqBHKPiiLPnpRDGFxyxee7uyWJFoBQ3owcCUabKHZigvZeehVfbxE7c= ccrow@ccrow-kubuntu
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvl7fpPqnLJJvZfZ40x65XLBt7uTYinvlaLj0AiARwsuxUMw9uILYK4gNoXg+wMixfUR/GwSqrI7VmFXpofhzqkyGRqr0g9NFrXbDVAZ0KfAAfbqnpGLpnenur1Xtl33a9QCuQ6m/kt3rwWwRM/uPF5PtG59D22hIH1SBxnQhPgLMC+ik+dE25OmAhk/lPmh0xssGbXRnYlKmSNf+zb30lnYXsbzfo3awi/J0Fksch2/k82GEbCEc/poZUcbLjaYJUkGvXQXJ1tbopOsklco+1b3nrqR/pZZSkhibqxns06bMW0NNoZaDCovnpou0HKPlje2miez9VAH//hxcE/gwXOIEkeDCYC6HAve65mdGt/pdet5HGEzwMkfI8fLIlKok1cEpsFljNeX1qDt0vtmkQxeorRiMFSi1vZjOVACmO2Avbt1mXDXDEcW9psIqM4Pc1DeXKRQdDyGj7ASwUZlmOCd7714PqJBiRRKVgwofafuVV/QgKXFtOId8TPMmhnU0= ccrow@ccrow-gentoo
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+lC8SjJpUSvlEb5hZRWnPqW3upFUSikevwAkERPb1d2RRTALBY4ayVvIw0p2O9hiVAcu7snGAxIhyedGXPRsJ2VkmmXXZtqXK3/2BPezGRwtwI40LUM4yuu8HZRYaeuJu4T30jx99IJkyVfmliwMuzGnMMSyRE1osntlhbOu/Jh7QxsCBYEzYSYMI/zxlapw6f5F0N+DasYa0h8NrY66c+NJKwck9LVPSAwvkd+Lx2EBRNw+RnsXx/IFpeHSPEn++3VM6o3blBD6ToAhy5YTtYcvNWgFVTseoZKBNiUc86XZVDDFZTLFlVq/bkkTu6mXwdS5sZZ6Enpv0ECwB3qRVZKXqUbLos6ll18Sz82MhF8XFa++LKNZp3BbeVTQA5WniON6znRol0Wblu1MxiJXHmsJOxfd+sm/Sq5q1yg7C9+1BlQfpW5Vjhc88akNi51ypR9I1j/AAM3Fl3jERbrgLK3QDmnNxNZ/3V8EJ4MfFOb2z9IOo55qrPrCUMHD0IQc= ccrow@turing4
        sudo: ['ALL=(ALL) NOPASSWD:ALL']
        shell: /bin/bash
    runcmd:
      - systemctl restart ssh
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-cloudinit-network
  namespace: gitlab
type: Opaque
stringData:
  networkData: |
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true

---

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: gitlab-runner
  namespace: gitlab
  labels:
    vm: gitlab-runner
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: gitlab-runner
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: harddrive
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
            - name: default
              model: virtio
              masquerade: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      networks:
        - name: default
          pod: {}
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: gitlab-runner-boot
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: gitlab-runner-cloudinit-userdata
          networkDataSecretRef:
            name: gitlab-runner-cloudinit-network


