apiVersion: rke-machine-config.cattle.io/v1
boot2dockerUrl: ""
cfgparam:
- disk.enableUUID=TRUE
cloneFrom: /Tac/vm/templates/jammy-server-cloudimg-amd64
cloudConfig: |+
  #cloud-config

cloudinit: ""
common:
  labels: null
  taints: []
contentLibrary: templates
cpuCount: "4"
creationType: template
customAttribute: []
datacenter: /Tac
datastore: /Tac/datastore/esx2-local1
datastoreCluster: ""
diskSize: "100000"
folder: null
gracefulShutdownTimeout: "0"
hostsystem: null
kind: VmwarevsphereConfig
memorySize: "12228"
metadata:
  creationTimestamp: "2023-12-21T18:49:15Z"
  generateName: nc-demo1-pool2-
  generation: 1
  name: nc-demo1-worker
  namespace: fleet-default
  resourceVersion: "590814"
  uid: 3381e714-c2c7-4c0e-8471-14dbab9c3b8d
network: []
os: linux
password: ""
pool: /Tac/host/Cluster1/Resources
sshPassword: tcuser
sshPort: "22"
sshUser: docker
sshUserGroup: staff
tag: []
username: ""
vappIpallocationpolicy: null
vappIpprotocol: null
vappProperty: []
vappTransport: null
vcenter: ""
vcenterPort: "443"
