apiVersion: rke-machine-config.cattle.io/v1
boot2dockerUrl: ""
cfgparam:
- disk.enableUUID=TRUE
cloneFrom: /Tac/vm/templates/jammy-server-cloudimg-amd64
cloudConfig: |+
  #cloud-config

cloudinit: ""
common:
  labels: null
  taints: []
contentLibrary: templates
cpuCount: "4"
creationType: template
customAttribute: []
datacenter: /Tac
datastore: /Tac/datastore/esx2-local1
datastoreCluster: ""
diskSize: "100000"
folder: null
gracefulShutdownTimeout: "0"
hostsystem: null
kind: VmwarevsphereConfig
memorySize: "8192"
metadata:
  creationTimestamp: "2023-12-21T18:49:15Z"
  generateName: nc-prod-pool1-
  generation: 1
  name: nc-prod-control
  namespace: fleet-default
  resourceVersion: "590813"
  uid: f5dc5755-6b60-4dda-8fe6-63d07446b47d
network: []
os: linux
password: ""
pool: /Tac/host/Cluster1/Resources
sshPassword: tcuser
sshPort: "22"
sshUser: docker
sshUserGroup: staff
tag: []
username: ""
vappIpallocationpolicy: null
vappIpprotocol: null
vappProperty: []
vappTransport: null
vcenter: ""
vcenterPort: "443"
