---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix-serve-deployment
  namespace: kiwix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix-serve
  template:
    metadata:
      labels:
        app: kiwix-serve
    spec:
      containers:
      - name: kiwix-serve
        image: ghcr.io/kiwix/kiwix-serve
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: kiwix-data
          mountPath: /data
        args: ["*.zim"]
      volumes:
        - name: kiwix-data
          nfs:
            server: 10.0.2.8
            path: /volume1/Archive/kiwix
---
apiVersion: v1
kind: Service
metadata:
  name: kiwix-serve-service
  namespace: kiwix
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kiwix-serve
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiwix-serve-ingress
  namespace: kiwix
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/16,174.21.143.8/32,104.167.184.2/32,131.191.29.18/32,192.173.169.229/32,73.97.37.245/32"
spec:
  rules:
  - host: kiwix.ccrow.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kiwix-serve-service
            port:
              number: 8080
  tls:
  - hosts:
    - kiwix.ccrow.org
    secretName: kiwix-serve-tls-secret

