apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: migrate01
  namespace: portworx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  clusterPair: stage
  includeResources: true
  startApplications: true
  namespaces:
    - pxbbq
  purgeDeletedResources: false
  selectors: 
    pxmigrate: "true"
