apiVersion: batch/v1
kind: Job
metadata:
  name: migratepvc
  namespace: cmd
spec:
  template:
    spec:
      containers:
      - name: cmd
        image: ccrow42/cmd:latest
        command: ["kubectl",  "apply", "-wle", "print bpi(2000)"]
      restartPolicy: Never
      remove: true
  backoffLimit: 4