apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-pxbbq-dr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: 'demo1'
    namespace: 'pxbbq'
  source:
    path: manifests/pxbbq/dr
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: pxbbq
