apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-pxbbq
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: 'demo2'
    namespace: 'pxbbq'
  sources:
    - repoURL: 'https://github.com/ccrow42/homelab'
      path: manifests/pxbbq/overlays/stage
      targetRevision: pxbbq-stage
    - repoURL: 'https://github.com/ccrow42/homelab'
      path: manifests/pxbbq/bbq-taster
      targetRevision: pxbbq-stage
  project: pxbbq
  syncPolicy:
    automated: {}