apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-pxbbq
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    name: 'demo2'
    namespace: 'pxbbq'
  source:
    path: manifests/pxbbq/overlays/stage
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: pxbbq
