apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns01
  namespace: cert-manager
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-prod-dns01
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    # this solver handles example.org challenges
    # and uses explicit credentials
    - selector:
        dnsZones:
          - "ccrow.org"
      dns01:
        route53:
          region: eu-east-1
          accessKeyID: AKIA3RIIOZYCG62JBON5
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
