---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: gitlab
spec:
  encryptedData:
    accesskey: AgBesMg2DXx8Lo34VUbZ2QY+iAjUmF3QVIFd2IJF2n0ffL3gJGr1+uf0tGjpFKG1nu/3yhzFNuVxwI6w13Z3lh/PD86WaKzuMrKM3DNibSRz1OZne7FuI7pFrKIGuSjyl+SMOoeIUgmS1LE8WZ1Z3ScUJ3ObJ/ftt15I9K/q3QdHey2rHcbrKIWq/+97AwXwSpT1or+5kxDsw9DrBd6NhUGEpbwxHLyC7b7hrJ6RdxPvbe0mBkMFYdl2++TUSCWWVEhgRTBXhnjVhXY3pfCKEBFlkP3R31p/Rxsx+iI1z2MlrQsFv1mXWm0v7i0nzox8Gl1TToiG8VpT//Jlkmax9dtEVs8kW9XSCvv1sHD1DvO9SCxFd1TA8d1fRp1sA8P+iQqYWTIdLyNwfviaF+HzMEBWxaNc0giumHuSt5CBNo1x3Hok/NMvk6wwuLgqiW19y6y0SpqxzE42vERSq3tPBgPfvtqQzFkQU+k0AGE5O6/Be7+91PFA5H8pn0WE9KKyB0iyDTBQN5VsnMRXg2ohVo951w6uzD0GNi0qloqW2pWdPaoegt+ZG1UslZQ/Qbj9LRH52/jlxTNi1LkY+2OHl7tlPO8XHezEyBfOyHxSlrXxhzeCoB2Iq1ICSEx37dUBxI01OjOhy6Pz0R4d8jxia5tmTuG0KOm8Al1xdO9YnERBedkt1G+q1OIaUSEvjgduavOqpy401N8=
    secretkey: AgCZe049v+v4HnF0fggYzyG8bxuQaXsglFLyPUcXR7UbnZpbbwGF/zrsKpGbuInl+A/UYZwMlSkK8xV3vC6zvoyLxs0X+w85hU93XL9mlTF1QGrXPpZmF8xclFLFx8KnthwYwF9VLYUAnBfDdmBw1CuXpZss02JIMyvCud9RVCg0oAYs33m94Dl8KOP6PhnslmK+TahZ++4fgwSkxzI2sfvV6vudbBJYf9kc4gTHiUKyCZfEioIi9M04BBPnwGTO0p4kNI8d846jv3FANKT9xDIUMz6olV/bgCKTsevbma9/hdimvX8H8zSzDFUqxA9UfmxRjzGlWhiqKM8+SYaKWVXDBm9NmvxXUEeasGnOQKt2PlFqzp1dMBgE/pXWyRd+/CbXC4qTc4+V+4BKaoJxOVwE1FdSlgK2y7H58cnmSzvs9WMFHAAuHysydnsqCObgy6E4Da3WMqyGA4USmqFTql6McVkkiEDsRLeL/0UwfHdJGqaB4Li7EFTKN84GbpuZcQBGrT/FyFSK3OBqwj+Z4u6eg3UTSvENC/ymo+HJ/GA1TVeEVXgblKwKEiA0lqlMqpXEgB44TPDjY1hfqWQnJjM5i8wMw5L1rrZkf1IHu1JWVmCDE0dUFOfLbD0X3sy2V7QZV1C/EloI9ltJ7E//O4Pis2+K4cMEa5LAdhDWnpBTWFoZBLmh20ON1/8urhBjQqMo+zkfG8OLqT5FJoa1OMcIiUoL
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: gitlab
