name: saml
label: 'authentik'
args:
  assertion_consumer_service_url: "https://gitlab.lan.ccrow.org/users/auth/saml/callback"
  idp_cert_fingerprint: '9d:48:05:10:1f:15:df:3e:68:dd:17:d8:cf:43:07:1d:4b:78:6e:59:46:8e:b2:df:26:16:85:0c:10:a1:ff:6f'
  idp_sso_target_url: "https://auth.ccrow.org/application/saml/gitlab/sso/binding/redirect/"
  issuer: "https://gitlab.lan.ccrow.org"
  name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
  attribute_statements:
    email:
      - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
    first_name:
      - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
    nickname:
      - "http://schemas.goauthentik.io/2021/02/saml/username"