apiVersion: v1
kind: Pod
metadata:
  name: cmd
  namespace: cmd
spec:
  serviceAccountName: cmd
  containers:
  - name: cmd-container
    image: bitnami/kubectl:1.27.8
    volumeMounts:
    - mountPath: /migration
      name: migration
    command: 
      - "bin/bash"
      - "-c"
      - "kubectl apply -f /migration/migration.yaml"
  volumes:
  - name: migration
    configMap:
      name: migration
      items:
      - key: migration.yaml
        path: migration.yaml