apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: cmd
spec:
  serviceAccountName: cmd
  containers:
  - name: kubectl-container
    image: ccrow42/cmd:latest
    command: ["/bin/sh", "-c", "kubectl version; exit 0"]
