apiVersion: v1
kind: Pod
metadata:
  name: cmd
  namespace: cmd
spec:
  serviceAccountName: cmd
  containers:
  - name: cmd-container
    image: bitnami/kubectl:1.27.8
    command: 
      - "bin/bash"
#      - "-c"
#      - "kubectl get pods -A"
  #rm: true  
  
