apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: asyncdr-schedule
  namespace: portworx
  annotations:
spec:
  template:
    spec:
      clusterPair: demo
      includeResources: true
      startApplications: false
      includeVolumes: true
      namespaces:
      - pxbbq
  schedulePolicyName: default-interval-policy
  suspend: false
  autoSuspend: true
