apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: genai
spec:
  template:
    spec:
      containers:
      - name: ollama
        resources:
          limits:
            nvidia.com/gpu: 1
