apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-pvc
  namespace: plexstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: ombi
    app.kubernetes.io/instance: prod-plexstack
  name: ombi-deployment
  namespace: plexstack
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ombi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ombi
    spec:
      containers:
      - env:
        - name: PUID
          value: "999"
        - name: PGID
          value: "999"
        image: ghcr.io/linuxserver/ombi
        imagePullPolicy: Always
        name: ombi
        ports:
        - containerPort: 3579
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: ombi-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ombi-config
        persistentVolumeClaim:
          claimName: ombi-pvc
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: "null"
  labels:
    app.kubernetes.io/instance: prod-plexstack
  name: ombi-service
  namespace: plexstack
spec:
  ports:
  - port: 3579
  selector:
    app: ombi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/instance: prod-plexstack
  name: ingress-ombi
  namespace: plexstack
spec:
  ingressClassName: nginx
  rules:
  - host: ombi.ccrow.org
    http:
      paths:
      - backend:
          service:
            name: ombi-service
            port:
              number: 3579
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ombi.ccrow.org
    secretName: ombi-tls