---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-browser-deployment
  namespace: browsetor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor-browser
  template:
    metadata:
      labels:
        app: tor-browser
    spec:
      containers:
      - name: tor-browser
        image: registry.lan.ccrow.org/domistyle/tor-browser
        ports:
        - containerPort: 5800
        - containerPort: 5900
        env:
        - name: DISPLAY_WIDTH
          value: "1920"
        - name: DISPLAY_HEIGHT
          value: "1080"
        - name: KEEP_APP_RUNNING
          value: "1"
        - name: TZ
          value: "UTC"
        volumeMounts:
          - name: private-data-desktop
            mountPath: /app/Browser/Desktop
          - name: private-data-downloads
            mountPath: /app/Browser/Downloads
      volumes:
      - name: private-data-desktop
        nfs:
          server: 10.0.2.8
          path: /volume1/tor-private/desktop
      - name: private-data-downloads
        nfs:
          server: 10.0.2.8
          path: /volume1/tor-private/downloads

---
apiVersion: v1
kind: Service
metadata:
  name: tor-browser-service
  namespace: browsetor
spec:
  type: ClusterIP
  ports:
  - port: 5800
    name: port5800
    targetPort: 5800
  - port: 5900
    name: port5900
    targetPort: 5900
  selector:
    app: tor-browser
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tor-browser-ingress
  namespace: browsetor
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/16,174.21.143.8/32,104.167.184.2/32,131.191.29.18/32,192.173.169.229/32"
spec:
  rules:
  - host: browsetor.ccrow.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tor-browser-service
            port:
              number: 5800
  tls:
  - hosts:
    - browsetor.ccrow.org
    secretName: tor-browser-tls-secret
