apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-externalsvc
spec:
  destination:
    name: 'in-cluster'
    namespace: 'externalsvc'
  source:
    path: manifests/externalsvc
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  