apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-jellyfin
spec:
  destination:
    name: 'in-cluster'
    namespace: 'jellyfin'
  source:
    path: manifests/jellyfin/overlay
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  