apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-dst
spec:
  destination:
    name: ''
    namespace: dst
    server: 'https://10.0.1.136:6443'
  source:
    path: manifests/dst
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
