apiVersion: batch/v1
kind: Job
metadata:
  name: post-taste
  namespace: pxbbq
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: cmd
      containers:
      - name: post-taste
        image: ccrow42/bbq-uploader:latest
        env:
        - name: MONGO_NODE
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: mongonode
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: mongopass
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: mongouser
        - name: S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3accesskey
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3bucket
        - name: S3_RESULTS_BUCKET
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3resultsbucket
        - name: S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3secretkey
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3url
      - name: scaledown
        image: bitnami/kubectl:1.27.8
        command: 
          - "bin/bash"
          - "-c"
          - "sleep 30 && kubectl -n pxbbq scale sts mongo --replicas=0 && kubectl -n pxbbq scale deployment pxbbq-web --replicas=0"
      - name: query-url
        image: curlimages/curl:latest
        command: 
          - "sh"
          - "-c"
          - "curl http://bbq-taster"
