---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgCDIxAv/Ma6ftf6anTN+ohw04g9uUsEJP52pNvjMOTG0mcyk69eTrM6OJzyifpko7IPZ2SsvSCJWSf4vvUCHa0cjjOZF06C0RDCjo4zglD8nVRmnsQCq4/nMkSw/PmKqc3l+XRQe6EYtwcZ2qdcYNkbz+cwyuI7MTM3seYCrFopY81TAoqqXLuCO4+xm8YbK3YVJsDBZsaQb0kQkin48sCtnFAh2BGiTAVyrRHzmr9n4Ut6Zp+5E0daY2moG01/8dcn9AYvq1CcXwgV2V6eZtXrXnlVRJytq8HfTe7Ff6DPHJVswjN4JZV6ESkryNlCAKy4JUhmNDTRgBdeR2ztIM1H/LUx623yt73B4OpGvEPH3yupaiQiyJuvTkeh80tZR/OJU5uKHUw/cCSTviIC91vaLpH7QMacC9QWIQxfxL4wDUmxYqKsePaYB8TiJXTl6J9PfRw1xbD5igsdkRi7zdDMyAsNKPxY3alP62qnD8DY6CuKUE4ibXOVVm+mnew4sWLxBthc84IkgV7SpuWlvy79/MeTgcUXTQTH9Uv1QVaD1ZyWJMyxI4lCqi46w0wHxJ+iuiS/1s/rzpv619KjDoGCjZVYCbjXTyAa1djaefES5HAvsaNyuTxabAepvHSdSrAzT/wujSKCNBzrktDgSQvKaX25UCEvowYjdwGZlyTrhePFpOcfTeAqWl/4XLItoBsoJnyBZdGsbMUp/1VRFX6f0dd5w2xjhP9+VhmWwVTNhs2NzUwrsNj2UQ==
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials-secret
      namespace: cert-manager
    type: Opaque
