apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-px-operator
spec:
  destination:
    name: 'demo2'
    namespace: 'portworx'
  source:
    path: manifests/px-operator/resources
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-portworx
spec:
  destination:
    name: 'demo2'
    namespace: 'portworx'
  source:
    path: manifests/portworx/overlays/demo2
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}

  