apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-metallb
spec:
  destination:
    name: 'demo1'
    namespace: 'metallb-system'
  source:
    path: manifests/metallb/overlays/demo1
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  