apiVersion: v1
kind: Secret
metadata:
  name: ddns-duckdns-secret
  namespace: pihole
data:
  DUCK_DNS_DOMAIN: <domain-base64-ecoded>
  DUCK_DNS_TOKEN: <duckdns-token-base64-ecoded>
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-duckdns
  namespace: pihole
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns-curl
            image: docker.io/curlimages/curl:7.73.0
            args:
            - /bin/sh
            - -c
            - curl -s "https://www.duckdns.org/update?domains=${DUCK_DNS_DOMAIN}&token=${DUCK_DNS_TOKEN}&ip="
            envFrom:
            - secretRef:
                name: ddns-duckdns-secret
          restartPolicy: OnFailure
