apiVersion: v1
kind: Secret
metadata:
  name: ddns-secret
  namespace: pihole
data:
  GOOGLE_USER: <user-base64-ecoded>
  GOOGLE_PASS: <password-base64-ecoded>
  GOOGLE_DOMAIN: <domain-base64-ecoded>
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-google
  namespace: pihole
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns-curl
            image: docker.io/curlimages/curl:7.73.0
            args:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=${GOOGLE_DOMAIN}"
            envFrom:
            - secretRef:
                name: ddns-secret
          restartPolicy: OnFailure
