loki:
  commonConfig:
    replication_factor: 3
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: 's3'
    s3:
      endpoint: minio.ccrow.org
      secretAccessKey: ***REDACTED***
      accessKeyId: loki
      s3ForcePathStyle: true
singleBinary:
  replicas: 3

