# http://10.0.4.101:8080/agent.x86_64.iso
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: purity-iso
  namespace: vmlab
spec:
  source:
    http:
      url: "http://10.0.4.101:8080/purity_6.8.7_202506052315+76a21ba50062-amd64.iso"
  storage:
    # Optional: Set the storage class or omit to accept the default
    storageClassName: longhornv2-iso
    volumeMode: Filesystem
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 16Gi
