apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externalsvc
spec:
  destination:
    name: 'in-cluster'
    namespace: 'externalsvc'
  source:
    path: manifests/externalsvc
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  source:
    path: manifests/argocd
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
spec:
  destination:
    name: 'in-cluster'
    namespace: 'heimdall'
  source:
    path: manifests/heimdall
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: browsetor
spec:
  destination:
    name: 'in-cluster'
    namespace: 'browsetor'
  source:
    path: manifests/browsetor
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
spec:
  destination:
    name: 'in-cluster'
    namespace: 'cert-manager'
  source:
    path: manifests/cert-manager/overlays/gentoo
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
spec:
  destination:
    name: 'in-cluster'
    namespace: 'jellyfin'
  source:
    path: manifests/jellyfin/overlay
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiwix
spec:
  destination:
    name: 'in-cluster'
    namespace: 'kiwix'
  source:
    path: manifests/kiwix
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
spec:
  destination:
    name: 'in-cluster'
    namespace: 'kubevirt'
  source:
    path: manifests/kubevirt/overlays/gentoo
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-manager
spec:
  destination:
    name: 'in-cluster'
    namespace: 'kubevirt-manager'
  source:
    path: manifests/kubevirt-manager/overlays/gentoo
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdi
spec:
  destination:
    name: 'in-cluster'
    namespace: 'cdi'
  source:
    path: manifests/cdi/overlays/gentoo
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
spec:
  destination:
    name: 'in-cluster'
    namespace: 'local-path-storage'
  source:
    path: manifests/local-path-provisioner/overlays/gentoo
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubemacpool
spec:
  destination:
    name: 'in-cluster'
    namespace: 'kubemacpool-system'
  source:
    path: manifests/kubemacpool
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: 'in-cluster'
    namespace: 'metallb-system'
  source:
    path: manifests/metallb/overlays/gentoo
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valheim
spec:
  destination:
    name: 'in-cluster'
    namespace: 'valheim'
  source:
    path: manifests/valheim
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smtprelay
spec:
  destination:
    name: 'in-cluster'
    namespace: 'smtprelay'
  source:
    path: manifests/smtprelay
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
spec:
  destination:
    name: 'in-cluster'
    namespace: 'mealie'
  source:
    path: manifests/mealie
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkwarden
spec:
  destination:
    name: 'in-cluster'
    namespace: 'linkwarden'
  source:
    path: manifests/linkwarden
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plexstack
spec:
  destination:
    name: 'in-cluster'
    namespace: 'plexstack'
  source:
    path: manifests/plexstack
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
spec:
  destination:
    name: 'in-cluster'
    namespace: 'plex'
  source:
    path: manifests/plex
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}