apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    volumeMounts:
    - name: custom-volume
      mountPath: /mnt
    - name: custom-volume2
      mountPath: /mnt2
  volumes:
  - name: custom-volume
    persistentVolumeClaim:
      claimName: rwx-volume
  - name: custom-volume2
    persistentVolumeClaim:
      claimName: rwx-volume-2

