apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    stork.libopenstorage.org/migrated: "true"
    stork.libopenstorage.org/migrationName: migrationschedule-interval-2023-01-26-185013
    stork.libopenstorage.org/migrationTime: 2023-01-26-190924
    stork.libopenstorage.org/resource-hash: "9131140452499544012"
  labels:
    io.kompose.service: dst-server
  name: dst-server
  namespace: dst
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.190.213
  clusterIPs:
  - 10.43.190.213
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "10999"
    nodePort: 30750
    port: 10999
    protocol: UDP
  - name: "11000"
    nodePort: 32598
    port: 11000
    protocol: UDP
  - name: "12346"
    nodePort: 31390
    port: 12346
    protocol: UDP
  - name: "12347"
    nodePort: 32281
    port: 12347
    protocol: UDP
  selector:
    io.kompose.service: dst-server
  type: LoadBalancer
