apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: jellyfin
  name: jellystat-db
spec:
  serviceName: jellystat-db
  replicas: 1
  selector:
    matchLabels:
      app: jellystat-db
  template:
    metadata:
      labels:
        app: jellystat-db
    spec:
      containers:
      - name: postgres
        image: postgres:15.2
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: jellystat-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jellystat-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "1Gi"
      volumes: []
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: jellystat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellystat
  template:
    metadata:
      labels:
        app: jellystat
    spec:
      containers:
      - name: jellystat
        image: cyfershepard/jellystat:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: jellystat-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jellystat-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jellystat-secret
              key: JWT_SECRET
        - name: POSTGRES_IP
          value: jellystat-db
        - name: POSTGRES_PORT
          value: "5432"
        - name: TZ
          value: "UTC"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: jellystat-backup-data
          mountPath: /app/backend/backup-data
      volumes:
      - name: jellystat-backup-data
        persistentVolumeClaim:
          claimName: jellystat-backup-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jellyfin
  name: jellystat-backup-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellystat-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  namespace: jellyfin
spec:
  tls:
  - hosts:
    - jellystat.lan.ccrow.org
    secretName: jellystat-tls
  rules:
  - host: jellystat.lan.ccrow.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellystat
            port:
              number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jellystat
  namespace: jellyfin
spec:
  selector:
    app: jellystat
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jellystat-db
  namespace: jellyfin
spec:
  clusterIP: None
  selector:
    app: jellystat-db
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jellystat-secret
  namespace: jellyfin
spec:
  encryptedData:
    JWT_SECRET: AgC0XU+Dd16Jybkbi1gfIW/JiDPIGKXnfASgP5lrmWfHQy6V6aSTfylMV1m2uL/JShhg2Rh0i3pXlomBsM5azV47YpICjIrlsWa2+3RM03sl9TrbWSO+KHgoadBzh+AB/i2V4DsX/C0dLL3G3EQWsAhoY+MECa55bfjK/n9LNmA5z9O2P7e5HfQNnAbZF/Hzy9xcOx5IyFpzLBI/cbh4hbWn/9wGA0RFHWjM6EvVWijxv9ZOiIej0Uq+xpTjUZQOF/PCaGyHeKVzAmX/aK+7LHpYcsrrWt+g1xiR99eZ+zNLPmxiO5cxg0kdGTO77WQ9C7Jdph6N2CR1zCGchiWGtWMjBWEe5EIdBNmUV2j8x5nCqwQlpgSMWopcIEaIRkPp/lfek3HNo6Nv0TKtFZLGKL305UACNu1u0M4H0dcFisXX63PG+YcP1ji+j2IECmMutZkRV9gRDPZAW6naqA5FGCbv5JIJvtVhv/+YejvG0cnWqerVsWUxVsgTKwGe2ZqnN0dYvWayEYX5rr10KXOJQyJXhjUkEKI/9fFlFbZ+QxN8DpOnc1ZbAwyqe7WGd7XPgeddYG1E1hv3YyrCGJvFI/gSabE6KRljb8wzJFbHu01jo82H0okLUHCVxWEZpQTxiuvG7jyGj2fM6TWmKG2sT93PQ+DR/ekf3QFCR3f4CjcG/vpoN98tQaTUDjtwDGiKCt00/0myyRCXiJtqmBHkVORm506/l43vDkDyQQy/Xh7CKO74edlH2Vf46TLkoQ==
    POSTGRES_PASSWORD: AgC5mBFGdZwXcN4/5kWk+I5Yc8qPnwuMLoASik4zn9fpTyFKYxGubl7qIWWU1TutTYcJf8Gj5zqtpbFdTgK09EmSupsObRvVJUWDoX/hb5HFVXwFBBwnRDpFk1roRl52D0KIBislF6x6b4w8yqfv4P5zn1N6Xnhm5/pW1oj01sKRNA0oYjI+d9xSpq+1sc4ycb+p6xshjWKVFjKl8rQrKTj1QlY9e00zsI6EX4zssHEpRpT0JkLg+7twoRlv7sQisgJRBYCpDEpawveTK3UOlTEatif0Un9zdoW7dnAvnL3GbJ+x7x9MaD80AvtF87fG76V0qrFTVN1B1Iy/Tk36oRJarJaDdNSpwWBzswmmftfkf8dB4U7xAI4L0UIqnMrLx5p52vnsjbMAnhMz3Fkcb6kB/dClGAdQulSSAUiXCHUm6CD2BwHkZ95rWXtTlt+281Rt8SRpMYgkXSYi1Nb7Ljltzv2t8YEaZxXhmAa8qn3SbL+SDgQ4Z2T7Yrq+/a8J8ibuyJTTTyLCiRMaNMvwf7bzPfE5p4W8Wn6oKxb5JrxRtC62atMUVWTCwgfwFfpq7jJabQyZDvXOLD0BhF030cPLzQ6P8supUvWAq9ZKazXbTn0UixgLdL5WRgIw9ILfRSPK6T1Lg0UT3mxZeTAwbklqDHaR7CKC3gFk8RvolJwB7dybF9hgE7sNjRnOVi9aWvKvDkdquciQS05SHmnbRA8r6a4DK2Nay7k=
    POSTGRES_USER: AgCJKAqSRIFpi7MPM65+s4JZrQZmwlmseea31YOKrLYcCWzdMOt9sA5o73sfG+dhWvf+qRh8gUHRKvNXglPpJeHpYjBOiVuKszeA6h9GvbkAvOP8nWNe6eQ5hVjaEgfh9OFOzDvTuf/sZLtidkNq3BdDFfAGJZmPzhxHpmyXg8pr/Vkyos5wXU/WFtYhvZ1RsmbMMtR91jM8IFX7jEnfVIZf17QZQQUs4fgAolNK5rptcMJ+5IdBskIAhUD9D+pIAlwSMV9jXXDYKqdI8V23hqU6tzVFbHNAZ3CuVNGZFpJ5npCcePQaizr0DMCADk2scydtfgfk1m21wGw+lMnXWaTqajruCKS+ezhCP4IR1rLHWG3IHb5u3AQqx/7yiUPad3MHS0gCEzR6MsMbraS7JvXC22fBp7/mKLgzZ4HTcl7jnp2coyXy5oyXrYHlp4a+Lf1QX9DmsxpJqVAbDRGg/Yn+m6kutv9ow7SjMg4U0P60EkmAP6AFhGC7ECnRJOiC55aoeiI/sv3XGmwR5dhmuIkksKuFRgMmhE4ajPDZqLjaNKOjUdFNiQcysg3Juh2Wl2VddnS0b7lpQkPGj4EBNP9rqXItOop/CaQ3zuaVTxxCAgnai8/Jn0QtTUdtd7mxAx9AtpRwAUyGt9M8sVCypmLOijhloCVWAXk1gdNjLgD9ItWDoyWtZW0LFrbPtpGiPIe5Kx6bMUayoQ==
  template:
    metadata:
      creationTimestamp: null
      name: jellystat-secret
      namespace: jellyfin