---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-secret
  namespace: jellyfin
spec:
  encryptedData:
    .dockerconfigjson: AgBnzuWazVHoP0JGu9yIZkNl2HNDWpt8t/Df/pEKkAWP2rpz3VCA8+M59LEL03oS/9uBJmV98vCGyUTqHr1WxVVzpWgnUvEHd6UqywCkRRyBfdwpebHzSVy9Cj+jDxFkz8Hony8ita66GVu390qnjTC81m0dNeD+SjeQnDzG8Z7eVLOtK4Vt2XOAC2uY5YV61ZgVfTyN9X/liD9X47ko9sYooIS7M+mYfwST0emLRfcq9WQILtakPCfZtMZmoF2GFVYJlcsuDiwJ+XrDxfReFm8kxgshkxvRC6Vg31vFm8KnSCtnHdr4LIkDUl4N2BSN2+CSQqaJZEijKR4RiJeqBWVP4o/nt3h+iAW2dQeG65tmJOlAsJWqCuDz1d/ZS0Vt18HNbiDHSWQ4D3U4rnoMl4BGV887j10ivTb6dXdRIXGMjV8YdVE0PownQlnkq7whzDWliNtNYOqK4qDV+Bjar6Hn7BvUeHwSq9c93aRbNAHjE3TRY6041JGWzlX8Y18Yq4CUpVsORT6URCRH/VkJ40PEQ5XmsGQUu8xyZ7OAlL9yus9m/Akpf/sN/c16JlDfBQFZRsbj9I14QbBDJflM9zncLwdv6oFjYQcK2OvpoK8Aa0lwb9U2U38eB8N/U5v5IJTRlViyibbZTYswz6GTGYDfIk5cEWdPRWOYn9ZOyU3hfF4ADQfWdzEr1c02Q8r5/uP8Wzc/CayWy0qEWpaahfS02M/5IcKeBvv7feBt4xciEwdsZh7Gg76y52gKIag1qAFfa3MnblOgZ3vqBrT/AahzqNaD908kIXHfxFkUOi5K4zSeka1WrULhfO9c9HT1/XCDtMqggBKA1MqB64JkoTaLy44bZYgOEqG9ANKc0a3FFUxG4xG9UwDUfDKTPu+MUg==
  template:
    metadata:
      creationTimestamp: null
      name: registry-secret
      namespace: jellyfin
    type: kubernetes.io/dockerconfigjson
