# Use as a way to load data into the RAG database
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: genai
  annotations:
  labels:
    app: pdf-bot
  name: pdf-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-bot
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        app: pdf-bot
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_DEFAULT_REGION
            - name: AWS_SECRET_ACCESS_KEY
            - name: EMBEDDING_MODEL
              value: sentence_transformer
            - name: LANGCHAIN_API_KEY
            - name: LANGCHAIN_ENDPOINT
              value: '"https://api.smith.langchain.com"'
            - name: LANGCHAIN_PROJECT
            - name: LANGCHAIN_TRACING_V2
              value: "false"
            - name: LLM
              value: llama2
            - name: NEO4J_PASSWORD
              value: password
            - name: NEO4J_URI
              value: neo4j://database:7687
            - name: NEO4J_USERNAME
              value: neo4j
            - name: OLLAMA_BASE_URL
              value: http://ollama:11434
            - name: OPENAI_API_KEY
          image: jowings/pdf_bot:v2
          name: pdf-bot
          ports:
            - containerPort: 8503
              hostPort: 8503
              protocol: TCP
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: genai
  labels:
    service: pdf-bot
  name: pdf-bot
spec:
  ports:
    - name: "8503"
      port: 80
      targetPort: 8503
      nodePort: 30008 #Modify this for your environment
  selector:
    app: pdf-bot
  type: LoadBalancer #Modify this for your environment
