# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.26.7&ns=portworx&b=true&iop=6&vsp=true&vc=10.0.1.10&vcp=443&ds=esx-local3&s=%22type%3Dthin%2Csize%3D100%22&r=17001&c=px-cluster-e6803b7e-dce9-4a4e-8356-f820678fd87a&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-prod
  namespace: portworx
  annotations:
    portworx.io/service-type: "portworx-api:LoadBalancer"
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.26.7&ns=portworx&b=true&iop=6&vsp=true&vc=10.0.1.10&vcp=443&ds=esx-local3&s=%22type%3Dthin%2Csize%3D100%22&r=17001&c=px-cluster-e6803b7e-dce9-4a4e-8356-f820678fd87a&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true"
spec:
  image: portworx/oci-monitor:3.0.1
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - type=thin,size=100
  secretsProvider: k8s
  startPort: 17001
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
  env:
  - name: VSPHERE_INSECURE
    value: "true"
  - name: VSPHERE_USER
    valueFrom:
      secretKeyRef:
        name: px-vsphere-secret
        key: VSPHERE_USER
  - name: VSPHERE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: px-vsphere-secret
        key: VSPHERE_PASSWORD
  - name: VSPHERE_VCENTER
    value: "10.0.1.10"
  - name: VSPHERE_VCENTER_PORT
    value: "443"
  - name: VSPHERE_DATASTORE_PREFIX
    value: "esx2-local3"
  - name: VSPHERE_INSTALL_MODE
    value: "shared"
