apiVersion: v1
kind: Secret
metadata:
 namespace: portworx
 name: px-vsphere-secret
type: Opaque
data:
 VSPHERE_USER: YWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2FsCg==
 VSPHERE_PASSWORD: {{VCENTER_PASSWORD}}
#dummy update 09