apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prodpool #the name of the pool you want to use
  namespace: metallb-system
spec:
  addresses:
  # be sure to update this with the address pool for your lab
  - 10.0.1.181 - 10.0.1.199
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: prod # the name of the advertisement
  namespace: metallb-system