apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-pvc-custom
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: portworx-rwx-kubevirt
