
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-portworx
spec:
  destination:
    name: 'demo1'
    namespace: 'portworx'
  source:
    path: manifests/portworx/overlays/demo1
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}

  