apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-portworx
spec:
  destination:
    name: 'demo2'
    namespace: 'portworx'
#    server: 'https://rancher.lan.ccrow.org/k8s/clusters/c-m-7m6pptnr'
  source:
    path: manifests/portworx/overlays/demo2
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default

  