apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hhk-ingress
spec:
  destination:
    name: ''
    namespace: hhk
    server: 'https://10.0.1.136:6443'
  source:
    path: prod/wordpress/hhk
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-amoc-ingress
spec:
  destination:
    name: ''
    namespace: amoc
    server: 'https://10.0.1.136:6443'
  source:
    path: prod/wordpress/amoc
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-art101-ingress
spec:
  destination:
    name: ''
    namespace: art101
    server: 'https://10.0.1.136:6443'
  source:
    path: prod/wordpress/art101
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false