apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-loki
spec:
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 4.8.0
    helm:
      valueFiles:
      - $values/prod/loki/loki-values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'loki'
    server: 'https://10.0.1.136:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false