apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pxbbq
  annotations:
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  source:
    path: argocd/pxbbq
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: pxbbq