apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-px-central
spec:
  sources:
  - repoURL: 'http://charts.portworx.io/'
    chart: px-central
    targetRevision: 2.5.0
    helm:
      valueFiles:
      - $values/prod/px-central/values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'central'
    server: 'https://10.0.1.136:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
