apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: rke2-01
  labels:
    vm: rke2-01
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/domain: rke2-01
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: harddrive
          - disk:
              bus: virtio
            name: pxvol
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
            - name: default
              model: virtio
              bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      networks:
        - name: default
          multus:
            default: true
            networkName: bridge-vlan5
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: rke2-01-boot
      - name: pxvol
        persistentVolumeClaim:
          claimName: rke2-01-px
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: rke2-01
            manage_etc_hosts: true

            network:
              version: 2
              ethernets:
                eth0:
                  dhcp4: false
                  addresses:
                    - 10.0.5.11/24
                  gateway4: 10.0.5.1
                  nameservers:
                    addresses:
                      - 10.0.5.1

            users:
              - name: ubuntu
                ssh_authorized_keys:
                  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+kx58yg6pGei4XrdXJhNfkRvfKWhGPUveM90+OGt74DbUc0B/BkfN5enpzEn3IciEOUm65TDQP0f1rmYxxWt9UPJWH2zvaWmaCdq0JUsf+V8N+G5gHpCVNJTMWeogtskpMGIKv7HJMH35RuBnM71ZHeMwTvhb422evYYq+8yUiRUc9B90p4w9Kshl+FjyOsSMn7m+9WS6HjX8Gbp+k8CGxqIrFz6t+ZE/uNmqlDaMZtXgJJIC+QrN/u14AfRX84VktNo4UPUgGmgrnCwk6fs6J5a55R6nEJ1qYHUnqkB+1AjwP2tZocHmeZkQilLT1kQvI3iIEHfyJya/c2zOZbiyu6XRsiYv/h28Ev6eevzoAQjeXq8IN/1PjZogRxgr7MpI/1GaHyq4SNBeCcgU6nk003kL6Y6o7GXTVaZbjCMdK6kF+Oi1MQtGygu4X9iy6pmCsSIIW+rFpqBHKPiiLPnpRDGFxyxee7uyWJFoBQ3owcCUabKHZigvZeehVfbxE7c= ccrow@ccrow-kubuntu
                sudo: ['ALL=(ALL) NOPASSWD:ALL']
                groups: sudo
                shell: /bin/bash

            runcmd:
              - systemctl restart networking

