apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rke2-01-boot
  annotations:
    volume.kubernetes.io/selected-node: gentoo-prime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rke2-01-boot
  annotations:
    volume.kubernetes.io/selected-node: gentoo-prime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-path