kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster
  namespace: portworx
  annotations:
    portworx.io/service-type: "portworx-api:LoadBalancer"
spec:
  cloudStorage:
    deviceSpecs:
    - type=thin,size=40