{
 "title": "Portworx Backup Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "le",
    "query": "\"0.1\",\"0.15\",\"0.25\",\"0.3\",\"0.5\",\"1\""
   },
   {
    "name": "grpc_service",
    "query": "label_values(grpc_server_handled_total,grpc_service) "
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "up{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Global Success Rate",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"OK\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"NotFound\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$interval])))\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_type=\"unary\"}[$interval]))"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "format": "ops",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(grpc_server_started_total{job=\"$job\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "process memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\"}",
       "legendFormat": "resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\"}",
       "legendFormat": "virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[30s])",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "gRPC request code",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(grpc_server_started_total{job=\"$job\"}[$interval])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Average handling time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(rate(grpc_server_handling_seconds_sum{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (grpc_service) * 1000",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "grpc_service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  { "title": "$grpc_service gRPC requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Request error percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "99%-tile latency of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Percentage of slow queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Portworx Cluster Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  {
   "title": "Portworx Cluster \"[[Cluster]]\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Usage Meter",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"[[Cluster]]\"})/sum(px_cluster_disk_total_bytes{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Avg. Cluster CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(px_cluster_cpu_percent{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "# Nodes (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"[[Cluster]]\"}) "
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(px_cluster_status_cluster_quorum{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "# Nodes online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_nodes_online{cluster=~\"[[Cluster]]\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=\"[[Cluster]]\"})-min(px_cluster_status_nodes_online{cluster=\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "CPU utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_cpu_percent{cluster =~ \"[[Cluster]]\"}"
    }
   ]
  },
  {
   "title": "Memory utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_memory_utilized_percent{cluster =~ \"[[Cluster]]\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}
{
 "title": "Etcd Dashboard",
 "description": "etcd sample Grafana dashboard with Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}} Resident Memory" }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  }
 ]
}
{
 "title": "Portworx Node Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" },
   { "name": "Instances", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Members",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"[[Cluster]]\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "PWX Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_cluster_disk_total_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_cluster_disk_utilized_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Instances \"[[Instances]]\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Usage: $tag_cluster - $tag_node",
     "expr": "px_cluster_cpu_percent{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_cpu_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Usage: $tag_node",
     "expr": "px_cluster_memory_utilized_percent{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_memory_utilized_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Memory Usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "IO Bytes TX",
     "expr": "px_network_io_bytessent{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes TX",
     "measurement": "px_network_io_bytessent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Bytes RX",
     "expr": "px_network_io_received_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes RX",
     "measurement": "px_network_io_received_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX  Disk IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_read_seconds {cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Read {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_write_seconds {cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Write  {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Used",
     "expr": "irate(px_disk_stats_write_bytes_seconds{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_disk_stats_read_latency_seconds{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_disk_stats_write_latency_seconds{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Portworx Volume Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "px_cluster_cpu_percent" },
   {
    "name": "Volumes",
    "label": "Volume Name",
    "query": "px_volume_depth_io {cluster=\"[[Cluster]]\"}"
   }
  ]
 },
 "panels": [
  { "title": "All Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Read Latency (1m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_read_latency_seconds{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Top n Volumes by Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk (10,(px_volume_usage_bytes{cluster=~\"[[Cluster]]\"}/px_volume_capacity_bytes{cluster=~\"[[Cluster]]\"})*100)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top n Volumes by IO depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,px_volume_depth_io{cluster=\"[[Cluster]]\"})",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Avg Write Latency (1m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_write_latency_seconds{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  { "title": "Volume: [[Volumes]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "Volumes" },
  {
   "title": "Current Replication Level (HA)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "px_volume_currhalevel{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{volumename}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O Priority",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "px_volume_iopriority{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{volumename}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_read_latency_seconds{cluster=~\"[[Cluster]]\",volumename=~\"[[Volumes]]\"})"
    }
   ]
  },
  {
   "title": "Avg Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_write_latency_seconds{cluster=~\"[[Cluster]]\",volumename=~\"[[Volumes]]\"})"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Disk Capacity",
     "expr": "px_volume_capacity_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " Capacity",
     "measurement": "px_volume_capacity_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Disk Usage",
     "expr": "px_volume_usage_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " Usage",
     "measurement": "px_volume_usage_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Configured Replication Level (HA)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "px_volume_halevel{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{volumename}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume total reads/writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_num_long_reads{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "No. of  Reads ",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_num_long_writes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "No. of  Writes ",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume IOPs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_iops{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "IOPs",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Read/Written Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_vol_read_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Read ",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_vol_written_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Written ",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Read Latency",
     "expr": "px_volume_vol_read_latency_seconds{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "Read Latency",
     "measurement": "px_volume_vol_read_latency_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Write Latency",
     "expr": "px_volume_vol_write_latency_seconds{volumename=~\"[[Volumes]]\"}\n",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "Write Latency",
     "measurement": "px_volume_vol_write_latency_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume IO Depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "px_volume_depth_io{volumename=~\"[[Volumes]]\"}",
     "legendFormat": "I/O Depth"
    }
   ]
  },
  {
   "title": "Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_readthroughput{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Read Throughput",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_writethroughput{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Written Throughput",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  { "title": "Cloud Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Last Backup Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "px_backup_stats_status{volumename=~\"[[Volumes]]\"}"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "px_backup_stats_duration_seconds{volumename=~\"[[Volumes]]\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup Duration (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "px_backup_stats_duration_seconds{volumename=~\"[[Volumes]]\"}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "px_backup_stats_size{volumename=~\"[[Volumes]]\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup Size (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "px_backup_stats_size{volumename=~\"[[Volumes]]\"}"
    }
   ]
  }
 ]
}