kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster
  namespace: portworx
  annotations:
    portworx.io/service-type: "portworx-api:LoadBalancer"
    argocd.argoproj.io/sync-wave: "2"    
spec:
  image: portworx/oci-monitor:3.2.1
  cloudStorage:
    maxStorageNodesPerZone: 5
    deviceSpecs:
    - type=thin,size=40
  stork:
    enabled: true
    args:
      admin-namespace: "portworx"
      webhook-controller: "true"
  security:
    enabled: false
    auth:
      guestAccess: 'Disabled'
