apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: smtprelay
data:
  main.cf: |
    myhostname = smtp.ccrow.org
    mydomain = ccrow.org

    inet_interfaces = all
    inet_protocols = ipv4

    mydestination =

    relayhost = 10.0.2.8:25
    relay_domains = ccrow.org

    local_transport = error:local delivery is disabled
    
    maillog_file = /dev/stdout
    
    smtpd_recipient_restrictions =
        permit_mynetworks,
        reject_unauth_destination

    mynetworks = 127.0.0.0/8 [::1]/128 10.0.0.0/8
