apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smtprelay
  namespace: smtprelay
spec:
  podSelector: {}
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0  # Allow all IPs (or narrow it down)
      ports:
        - port: 25
          protocol: TCP
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - podSelector: {}
    - to:
        - ipBlock:
            cidr: 10.0.2.8/32
      ports:
        - port: 25
