---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbq-taster
  namespace: pxbbq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbq-taster
  template:
    metadata:
      labels:
        app: bbq-taster
    spec:
      containers:
      - name: bbq-taster
        image: ccrow42/bbq-taster:latest
        env:
        - name: MONGO_NODE
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: mongonode
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: mongopass
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: mongouser
        - name: S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3accesskey
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3bucket
        - name: S3_RESULTS_BUCKET
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3resultsbucket
        - name: S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3secretkey
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              name: bbq-taster
              key: s3url
---
apiVersion: v1
kind: Service
metadata:
  name: bbq-taster
  namespace: pxbbq
spec:
  selector:
    app: bbq-taster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
