apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- mongodb.yaml
- pxbbq.yaml
- bbq-taster.yaml
#- bbq-taster-secret.yaml removed as we are using automation now