apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-docker-registry-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.1.8
    path: /volume1/k3s/registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-nfs
  namespace: registry
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi