apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../resources
- ./ingress.yaml
patches:
- path: pxbbq-web-service.yaml
- path: mongodb-sts.yaml
- path: pxbbq-web-deployment.yaml