apiVersion: batch/v1
kind: Job
metadata:
  name: scaledown
  namespace: pxbbq
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: cmd
      restartPolicy: Never
      containers:
      - name: cmd-container
        image: bitnami/kubectl:1.27.8
        command: 
          - "bin/bash"
          - "-c"
          - "kubectl -n pxbbq scale sts mongo --replicas=0"

