## Harness GitOps Agent - Overrides File
## For default overrides, please refer to https://github.com/harness/gitops-helm/blob/main/values.yaml
## Argo CD overrides can be found at https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

# <---Argo CD image details--->
global:
  image:
    repository: harness/argocd
    tag: v2.9.4

# <---Harness configuration overrides--->
harness:
  identity:
    accountIdentifier: k__YmOVDQO-Aq9TQjuoF7g
    orgIdentifier: default
    projectIdentifier: default_project
    agentIdentifier: demo2

  secrets:
    agentSecret: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUM2S1djM2dQS3RRRVBvCkdScjhoZE5QNU9vZGdDa2xUV2NucGFnRDUwbkluOGNSNDM5N0VaNktGUzN0WCtkTXVUejFnSDVFRUF3QlltamEKeEl0cE5jWmloaXBlb0FuK3FMUXlKVnlOTHRKMStuQkZibDM2UHNjZk5ab1dJOWRCNHhzazNHdHFNR0NEWmpibwpPYzNRc2MyL1hweGwyd0FibmFGTUFINnBwY3NkZnRwb3FPeWFUR3ZDSjUydVArSktGcUloZzlTdEtoQnA2ZVJLCjRSM2pROFlIMzBNZFVrU3NoZ3IxVlZ0K2xiSTFnN1JOZERwWlM2WVBWZllNMGh6WmJlS2pUUWl2djIrdE0wUVQKUmdDTjBqV0pXK3lXRnFNV0Flb3U0Mk9nOHlHa09VRlpjckdUdCtLd3Jld0F0SGkvRHo2bGpJWEVablA0cFFvMQptNUpIWFhzVEFnTUJBQUVDZ2dFQVAxYTY4WjJEOUFKN21FcUNiZ3l5V3VxTjVUK253RE5YdDV1YlVNaXV4LzNrCjQyYytCb2QySTVFVk1VQ0NHQTZtZVBrZy9OTmc0ayt6VVV1eUN6ZnFxYmJ3VDRXd0lOOFJnRVpKK1JkSE1ERG4KWmhncERXMnluaUhFcldmQVk0Qjd5Y3pkRnlJaWxGS0F0LzZDMGxETXFpSHNvSk1rdEVDcmtvcFFqalFFcWFIYwp6aE53TjBNWVlnRmc1OWdoSTluWFkwOExhZnE3Z2x1YzBQMGRUY0xOWVU0WWJPOGZLV204elFzV0NoQjJvNEZmCmhHcGRKS1RCeE84eU9tYUVMQlhWTUlYRGpUdlBuSlFsR3RxNmxQT2MxS0RWL0RIU2FJV08vQm0xMTVpZXhpWUwKdGh6OGtiN1kxc0Q5WW8wckh6MVNaNEg0Z2xVL2duY2JaVHFIWVRCYm9RS0JnUURSeEtEZjNCS0NpN2t5SjFySwpDUzNzVmJibFZKTzFqTHc3ZEVKbHJaaElaVFhYeUpnTUQyVW9QcUJOQjZCcmJmQ3o0SUlmU0tzTm0rcUxDQUpsCnZtbzRSejk1VmhsZXJmckxlK2JpZkJVZjFxbFZJck9HczMvbGRlTGtSRHc4cEpXUWVUc2dNZVd2bDVBUVlzdU4KNjNMK1AxVG41MkFRQm5XQzU1VzdSRTZMcVFLQmdRRGpNT0F2VnB1ajJ3dm5aQ280bTFnSmhqTGFoKzdEYTBhRAplUWRtQ3VuNnVzRXdEaFJZUDdXK2JOMGN1OUNCdVA1UUd1ZXB5SWRiR2NuNzQ0Z0ZzazhVZkFjVmV5SlpMeDhhCkhZbm16ZHlSV0JKVnVQYWNJOGJpNFl0WSttajdNWmc4RVY2N2s4cmVQSHJJUS9DRmVBNlUrd3o2QVZTSDZFZzIKeGpTSmVUam1Xd0tCZ0FUSjBFSkw2OEEvSUVNYzB0MjV4K3FWS2sraDFwMVdVUldxV2Jtb2RNbHlSZ0JlKzltSwpvR3lDd1hZQXJwREZPYkZoZHBid09iZGR6OFRNc2dGUWoyd3BkREY0M2F0am5VMzN6aFZ0YjY0Q1lHc3BGNkFECmlPL2IrUW5zNU5NZGpxeDFsL3ZzSjZvU2M1OXNJZWxqYm9TUFBZanRweXUyZWdnNjhSZ05QeDNCQW9HQVh3UWsKN29kcFJta3BIRmdlOUZlN3hSZjBFc05CRDBmQlVPRUFRQ1FXWVQ5VDVwWXMyZytqSWdZRG42M0k4VWYrVEdCRQpQUlRaenpjRTY2em9TWUdlWXpIUUFLTGo1YXE0ZGtLZVZ3SUgybDJjSlcvYTY4aG11S0tkbGRQOHJmbTY4bnhOClEyUDNOMlRSOFFuQkFRRUtFRExDNVpoQzB5aEpjMmNIdCtzVDZmc0NnWUF0Z0d0b3NrSndyT0dhK3VlNG01VXUKa2RMNThOWFZ0Z3lVQ1hxdHJPa3p5K2VIbkpOTHYvcTFJKzcvSW5MQzJCTnEyejFTZFJ4bW4vYjRld0xDSXdzSQp2WUpvZ2VPN29HYjI4cWlmaEMrUHpnRmt3cFIyQnlQU3l4eGFya0dIZzVuRitoc0VpVHg0N0oyRms5N251eWR5CktaVjlTaGdSY29oa3M1cFhTWWl2MkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
    # <---CA data overrides--->
    caData:
      enabled: false
      secret: 

  gitopsServerHost: https://app.harness.io/prod1/gitops
  networkPolicy:
    create: true
  createClusterRoles: true

  configMap:
    logLevel: debug

    # <---Agent communication protocol details--->
    http:
      agentHttpTarget: https://app.harness.io/gitops
      tlsEnabled: false
      certPath: /tmp/ca.bundle

  # <---Disaster Recovery override values--->
  disasterRecovery:
    enabled: false
    identifier: 

  # <---Openshift override values--->
  openshift:
    enabled: false

# <---Argo CD configuration overrides--->
argo-cd:
  enabled: true

  ## IMPORTANT: Mark crds as false for Helm installations if they are already installed in the cluster
  crds:
    install: true

  configs:
    cm:
      cluster.inClusterEnabled: true

  # <---Redis image details--->
  redis:
    enabled: true
    image:
      repository: redis
      tag: 7.0.11-alpine

  # <---High Availability Agent (HA) values--->
  redis-ha:
    enabled: false
    haproxy:
      enabled: false
      image:
        repository: haproxy
        tag: 2.6.14-alpine

  repoServer:
    replicas:  1 
    env:
      - name: HELM_PLUGINS
        value: /helm-sops-tools/helm-plugins/
      - name: HELM_SECRETS_CURL_PATH
        value: /helm-sops-tools/curl
      - name: HELM_SECRETS_SOPS_PATH
        value: /helm-sops-tools/sops
      - name: HELM_SECRETS_KUBECTL_PATH
        value: /helm-sops-tools/kubectl
      - name: HELM_SECRETS_BACKEND
        value: sops
      - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
        value: "false"
      - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
        value: "true"
      - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
        value: "false"
      - name: HELM_SECRETS_WRAPPER_ENABLED
        value: "true"
      - name: HELM_SECRETS_HELM_PATH
        value: /usr/local/bin/helm
    

    # <---SOPS override values--->
    initContainers:
      - name: sops-helm-secrets-tool
        image: harness/gitops-agent-installer-helper:v0.0.1
        imagePullPolicy: IfNotPresent
        command: [ sh, -ec ]
        args:
          - |
            cp -r /custom-tools/. /helm-sops-tools
            cp /helm-sops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /helm-sops-tools/helm
            chmod +x /helm-sops-tools/*
        volumeMounts:
          - mountPath: /helm-sops-tools
            name: helm-sops-tools

# <---Agent overrides--->
agent:
  harnessName: demo2
  image:
    repository: harness/gitops-agent
    tag: v0.72.0

  replicas:  1 
  # <---Agent Proxy Config overrides--->
  proxy:
    enabled: false
    httpProxy: 
    httpsProxy: 

# <---Agent upgrader overrides--->
upgrader:
  enabled: true
  image: harness/upgrader:latest