apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-sc
parameters:
  io_profile: db_remote
  priority_io: high
  repl: "3"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true


