---
- name: update authorized keys
  hosts: all
  become: yes
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: https://raw.githubusercontent.com/ccrow42/homelab/main/ansible/authorized_keys