---
- name: update authorized keys
  hosts: turing
  become: yes
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: https://raw.githubusercontent.com/ccrow42/homelab/main/ansible/authorized_keys
    - name: Set root authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        key: https://raw.githubusercontent.com/ccrow42/homelab/main/ansible/authorized_keys-root
    - name: Hardening sshd
      block:
       - name: Editing sshd config
         lineinfile:
           dest: "/etc/ssh/sshd_config"
           regexp: "{{ item.regexp | default(omit) }}"
           line: "{{ item.line }}"
           state: "{{ item.state | default('present') }}"
           validate: "sshd -t -f %s"
         with_items:
           - regexp: "^PermitRootLogin\ "
             line: "PermitRootLogin without-password"
           - regexp: "^PasswordAuthentication\ "
             line: "PasswordAuthentication no"
           - regexp: "^PermitEmptyPasswords\ "
             line: "PermitEmptyPasswords no"
       - name: Reload sshd
         service:
           name: sshd
           state: reloaded
