---
- name: update authorized keys
  hosts: all
  become: yes
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: https://github.com/ccrow42/homelab/ansible/authorized_keys