apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amoc
  namespace: amoc
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector: 
            matchLabels:
              kubernetes.io/metadata.name: amoc
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kuma
          podSelector:
            matchLabels:
              app: uptime-kuma
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              name: rke2-ingress-nginx
  egress:
    - to:
        - podSelector: {}
          namespaceSelector: 
            matchLabels:
              kubernetes.io/metadata.name: amoc
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
