apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incluster-testsecret
spec:
  destination:
    name: 'in-cluster'
    namespace: 'default'
  source:
    path: manifests/argocd/test-secret
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  