apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-valheim
spec:
  destination:
    name: 'prod'
    namespace: 'valheim'
  source:
    path: manifests/valheim
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  