apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-testsecret
spec:
  destination:
    name: 'prod'
    namespace: 'default'
  source:
    path: manifests/argocd/test-secret.yaml
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  