apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-plexstack
spec:
  destination:
    name: 'prod'
    namespace: 'plexstack'
  source:
    path: manifests/plexstack
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  