apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-certmanager
spec:
  destination:
    name: 'prod'
    namespace: 'cert-manager'
  source:
    path: manifests/cert-manager/overlays/prod
    repoURL: 'https://github.com/ccrow42/homelab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  