apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-noble-cloudimg
  namespace: default
spec:
  source:
    http:
      url: "http://registry.lan.ccrow.org:8080/noble-server-cloudimg-amd64.img"
  storage:
    # Optional: Set the storage class or omit to accept the default
    storageClassName: longhornv2-iso
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: windows11-iso
  namespace: default
spec:
  source:
    http:
      url: "http://registry.lan.ccrow.org:8080/Windows11_Unattended.iso"
  storage:
    # Optional: Set the storage class or omit to accept the default
    storageClassName: longhornv2-iso
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 12Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: windows10-iso
  namespace: default
spec:
  source:
    http:
      url: "http://registry.lan.ccrow.org:8080/Windows.iso"
  storage:
    # Optional: Set the storage class or omit to accept the default
    storageClassName: longhornv2-iso
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 12Gi