apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-block-ubuntu-noble-cloudimg
  namespace: default
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
  storage:
    # Optional: Set the storage class or omit to accept the default
    storageClassName: longhorn
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi