apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan7
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan7",
      "type": "bridge",
      "bridge": "br7",
      "ipam": {
        "type": "dhcp"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan4
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan4",
      "type": "bridge",
      "bridge": "br4",
      "ipam": {
        "type": "dhcp"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan5
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan5",
      "type": "bridge",
      "bridge": "br5",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.0.5.0/24",
              "rangeStart": "10.0.5.150",
              "rangeEnd": "10.0.5.250",
              "gateway": "10.0.5.1"
            }
          ]
        ],
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.0.5.1" }
        ],
        "dataDir": "/opt/local-host-ipam/container-ipam-state"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan11
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan11",
      "type": "bridge",
      "bridge": "br11",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.0.11.0/24",
              "rangeStart": "10.0.11.150",
              "rangeEnd": "10.0.11.250",
              "gateway": "10.0.11.1"
            }
          ]
        ],
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.0.11.1" }
        ],
        "dataDir": "/opt/local-host-ipam/container-ipam-state"
      }
    }'