apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan7
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan7",
      "type": "bridge",
      "bridge": "br7",
      "ipam": {
        "type": "dhcp"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan5
  namespace: vmlab
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-vlan5",
      "type": "bridge",
      "bridge": "br5",
      "ipam": {
        "type": "dhcp"
      }
    }'