apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool  #the name of the pool you want to use
  namespace: metallb-system
spec:
  addresses:
  - 10.0.5.61 - 10.0.5.70 # be sure to update this with the address pool for your lab
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: prod # the name of the advertisement
  namespace: metallb-system
