apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources: {}
    volumeMounts:
    - mountPath: "/mnt"
      name: rwx-pvc
    command: ['sleep', '3600']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: rwx-pvc
      persistentVolumeClaim:
        claimName: rwx-volume

status: {}
