apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: 30-min
policy:
  interval:
    intervalMinutes: 30  
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: migrationschedule
  namespace: portworx
spec:
  template:
    spec:
      clusterPair: demo
      includeResources: true
      startApplications: false
      includeVolumes: true
      namespaces:
      - pxbbq
  schedulePolicyName: 30-min
  suspend: false
  autoSuspend: true