name: deploy latest px-central

on:
  push:
    branches:
      - main
    paths:
      - 'armory/px-central.yaml'
      - 'manifests/px-central.yaml'

jobs:
  build:
    name: deploy from main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Replace central db secret
        run: |
          sed -i 's|{{PXCDB_PASSWORD}}|'"${{ secrets.PXCDB_PASSWORD }}"'|' px-central.yaml
        working-directory: manifests/px-central
      - name: Deployment
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"
          clientSecret: "${{ secrets.CDAAS_CLIENT_SECRET }}"
          path-to-file: "/armory/px-central.yaml"



