---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: externalsvc
spec:
  encryptedData:
    auth: AgCJFpMKP2tSdYLZA59sPfscdsMm6wnQ9ijQkDT1mbZKOgFKxy/r7YUBwh9uerM1n5yCW2y8kB9IIIEle21rXafquCd+Pxf6iM/qqecfNA4CO40LYgcO18Zu6GtJWH9tucE0kbNhITAluF+FzJGjF4rbWC2620H2KW7Dbdo12D6wsNb3NzbeLK8xYXCVzC8kVHBjFFbcUcABBbnSIkJB9R2sahIbZC3Zg8JkIf4kADiz38deKbIsvnl4mf2ZcryS5fIKloPG0W4qdw69hU/c6MxoCmQBJjkt67+sjsZDX9bp9mgf9Lvj2v+otiYPWKz8xjTugDqmSjOqhS21t7HiCaByfzMAtzdOQN2eqlPQth8em4t8lqYGW1f6H3hWI8b8tA+WD00UEDgOa+n9czz/wn5gqSgZWR+qBhmT7fnHXElVtzN3s7A0xmd8XWGgPSKRckGNwUrnXBn2vNxmynAcuKwzhrr3H5tcMgbiVzjkhkU6x3Fnm98FDFc5aO0pBgeVb8fwRvPi8TJ5F0G1n29nkF5NSkjrOgwbxUjproyoR6Bx2x0eL/nzngJoWkWviF56OMFnhU1/Kd2I8cSU1AKFKF3BwvJOLcpKFnx10ZHJaywbH5leT/m7PSqyJRcYaCLTP9aCA8r5ePoGfK/m1+nktgMyGnwAYgo2Hqvoad8+bGM2Viy7BfvPekSPP8uwcY0lgg3G/W1/O6pQv5CHfNhWjV98gRMupOZ8veJC+Uwv6y+R0Jq5IaNBVEFiPFD0
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: externalsvc
